---
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=TZ=America/Denver
      - WEBUI_PORT=9090
      - TORRENTING_PORT=6881
    volumes:
      - /myDockers/qBittorrent/appdata:/config
      - /mnt/Big Olive/s2mccaffr/qbittorrent-downloads:/data/downloads
    ports:
      - 9090:9090
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
