# MediaWiki with MySQL
# Access via "http://localhost:8080"
#   (or "http://$(docker-machine ip):8080" if using docker-machine)
services:
  mediawiki:
    image: mediawiki
    restart: always
    networks:
      - docker_network
    ports:
      - 8080:80
    volumes:
      - /var/www/html/
      - ./LocalSettings.php:/var/www/html/LocalSettings.php
  database:
    image: mysql:5.7
    restart: always
    networks:
      - docker_network
    environment:
      MYSQL_DATABASE: my_wiki
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: wikimedia
      MYSQL_PASSWORD: wikimedia
    volumes:
      - /var/lib/mysql
networks:
  docker_network:
    driver: bridge

